spring:
  datasource:
    url: jdbc:mysql://:3306/weather?characterEncoding=utf-8&useSSL=false
    username: weather
    password:
  jpa:
      show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG